name: Deploy Go Application

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checktout@v4
      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t daman07/nusantara_service .
      - name: Push image to docker hub
        run: docker push daman07/nusantara_service:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull daman07/nusantara_service:latest
      - name: Delete old container
        run: docker rm -f nusantara-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name nusantara-container daman07/nusantara_service
